[tool.isort]
profile = "black"

[tool.mypy]
ignore_missing_imports = true

[tool.pylint.messages_control]
disable = [
    "C0103",
    "R0913",
    "R0801",  # allow 'similar lines'
]
max-line-length = 120

[tool.pyright]
